import { UnitPatternVO } from '@/valueObjects';

const unitPatternPresets: UnitPatternVO[] = [
  [
    [null, null, null, null, null],
    [null, null, null, null, null],
    [null, true, true, true, null],
    [null, null, null, null, null],
    [null, null, null, null, null],
  ],
  [
    [null, null, null, null, null],
    [null, null, true, null, null],
    [null, null, true, null, null],
    [null, null, true, null, null],
    [null, null, null, null, null],
  ],
  [
    [null, null, null, null],
    [null, true, true, null],
    [null, true, true, null],
    [null, null, null, null],
  ],
  [
    [null, null, null, null, null],
    [null, null, true, null, null],
    [null, true, null, true, null],
    [null, null, true, null, null],
    [null, null, null, null, null],
  ],
  [
    [null, null, null, null, null],
    [null, null, true, null, null],
    [null, true, null, true, null],
    [null, true, null, true, null],
    [null, null, true, null, null],
    [null, null, null, null, null],
  ],
  [
    [null, null, null, null, null],
    [null, true, true, null, null],
    [null, true, null, true, null],
    [null, null, true, null, null],
    [null, null, null, null, null],
  ],
  [
    [null, null, null, null, null],
    [null, true, null, null, null],
    [null, null, true, true, null],
    [null, true, true, null, null],
    [null, null, null, null, null],
  ],
  [
    [null, null, null, null, null, null],
    [null, null, true, null, null, null],
    [null, true, null, true, null, null],
    [null, null, true, null, true, null],
    [null, null, null, true, null, null],
    [null, null, null, null, null, null],
  ],
  [
    [null, null, null, null, null, null],
    [null, null, true, null, null, null],
    [null, true, null, true, null, null],
    [null, true, null, null, true, null],
    [null, null, true, true, null, null],
    [null, null, null, null, null, null],
  ],
  [
    [null, null, null, null, null, null],
    [null, null, true, true, null, null],
    [null, null, null, null, true, null],
    [null, true, null, null, null, null],
    [null, null, true, true, null, null],
    [null, null, null, null, null, null],
  ],
  [
    [null, null, null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, true, null, null, null, null, null],
    [null, null, null, null, true, null, true, null, null, null, null],
    [null, null, null, null, true, null, true, null, null, null, null],
    [null, null, true, true, null, null, null, true, true, null, null],
    [null, true, null, null, null, null, null, null, null, true, null],
    [null, null, true, true, null, null, null, true, true, null, null],
    [null, null, null, null, true, null, true, null, null, null, null],
    [null, null, null, null, true, null, true, null, null, null, null],
    [null, null, null, null, null, true, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null],
  ],
];

export default unitPatternPresets;
