export enum CommandNameEnum {
  AddPlayer = 'ADD_PLAYER',
  RemovePlayer = 'REMOVE_PLAYER',
  MovePlayer = 'MOVE_PLAYER',
  ChangePlayerAction = 'CHANGE_PLAYER_ACTION',
  ChangePlayerPrecisePosition = 'CHANGE_PLAYER_PRECISE_POSITION',
  SendPlayerIntoPortal = 'SEND_PLAYER_INTO_PORTAL',
  TeleportPlayer = 'TELEPORT_PLAYER',
  ChangePlayerHeldItem = 'CHANGE_PLAYER_HELD_ITEM',
  CreateStaticUnit = 'CREATE_STATIC_UNIT',
  RemoveStaticUnit = 'REMOVE_STATIC_UNIT',
  CreateFenceUnit = 'CREATE_FENCE_UNIT',
  RemoveFenceUnit = 'REMOVE_FENCE_UNIT',
  CreatePortalUnit = 'CREATE_PORTAL_UNIT',
  RemovePortalUnit = 'REMOVE_PORTAL_UNIT',
  CreateLinkUnit = 'CREATE_LINK_UNIT',
  RemoveLinkUnit = 'REMOVE_LINK_UNIT',
  CreateEmbedUnit = 'CREATE_EMBED_UNIT',
  RemoveEmbedUnit = 'REMOVE_EMBED_UNIT',
  CreateColorUnit = 'CREATE_COLOR_UNIT',
  RemoveColorUnit = 'REMOVE_COLOR_UNIT',
  CreateSignUnit = 'CREATE_SIGN_UNIT',
  RemoveSignUnit = 'REMOVE_SIGN_UNIT',
  RotateUnit = 'ROTATE_UNIT',
}
